---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        traefik_entrypoints:
          - name: custom
            port: 8096
        traefik_http_routers:
          - name: test-app
            rule: "Host(`test.example.com`)"
            service: test-app
            tls: true
          - name: test-http-only
            rule: "Host(`http.example.com`)"
            service: test-http-only
            tls: false
          - name: test-custom-port
            rule: "PathPrefix(`/`)"
            service: test-custom-port
            tls: false
            entrypoint: custom
        traefik_services:
          - name: test-app
            urls:
              - "http://127.0.0.1:8080"
          - name: test-http-only
            urls:
              - "http://127.0.0.1:9090"
          - name: test-custom-port
            urls:
              - "http://127.0.0.1:8096"
